---
name: Publish Packages to npmjs

on:
  release:
    types: [published]

jobs:
  # build-image:
  #   name: Build Image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Docker Build, Run Tests, and Publish Packages
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: false
  #         tags: ${{ github.run_id }}
  #         target: test_and_publish
  #         secrets: |
  #           NPM_FE_SHARED_TOKEN: ${{ secrets.NPM_FE_SHARED_TOKEN }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run publish:packages
        env:
          NPM_FE_SHARED_TOKEN: ${{ secrets.NPM_FE_SHARED_TOKEN }}
